### PR TITLE
bug/62: Fixed unstable tests

### LINKED ISSUE #62: Tests interfer
Currently the tests influence each other since the files from BucketFS are not cleaned before each test run.

Solution:

Add timestamp prefix to test files

### PR DESCRIPTION
**Pull request by jakobbraun**
Closes #62

### CODE REVIEW

File: src/test/java/com/exasol/adapter/document/files/AbstractDocumentFilesAdapterIT.java [hunk 1]
```diff
@@ -102,42 +114,49 @@ void testJsonDataTypesAsJson() throws SQLException {
...
                     () -> assertThat(getPushDownSql(getStatement(), query), endsWith("WHERE TRUE")), // no post
                     // selection
                     () -> assertThat(getSelectionThatIsSentToTheAdapter(getStatement(), query),
-                            equalTo("BOOKS.SOURCE_REFERENCE='testData-1.json'"))//
+                            equalTo("BOOKS.SOURCE_REFERENCE='" + dataFilesDirectory + "/testData-1.json'"))//
             );
         }
     }
 
     // @Test //TODO re-enable when SUPPORT-18306 is fixed; See #41
```
Comment (morazow) [inline src/test/java/com/exasol/adapter/document/files/AbstractDocumentFilesAdapterIT.java:146]: Do you need this? Support ticket shows resolved.

File: src/test/java/com/exasol/adapter/document/files/AbstractDocumentFilesAdapterIT.java [hunk 2]
```diff
@@ -146,21 +165,26 @@ void testFilterWithOrOnSourceReference() {
      */
     @Test
     // TODO remove when SUPPORT-18306 is fixed
```
Comment (morazow) [inline src/test/java/com/exasol/adapter/document/files/AbstractDocumentFilesAdapterIT.java:167]: Here also.

File: src/test/java/com/exasol/adapter/document/files/AbstractDocumentFilesAdapterIT.java [hunk 3]
```diff
@@ -44,30 +45,41 @@
...
+        }
+    }
+
+    protected abstract void createVirtualSchema(String schemaName, String mapping);
 
     @Test
-    void testReadJson() throws SQLException {
-        createJsonVirtualSchema();
+    void testReadJson() throws SQLException, IOException {
+        final String dataFilesDirectory = String.valueOf(System.currentTimeMillis());
```
Comment (morazow) [inline src/test/java/com/exasol/adapter/document/files/AbstractDocumentFilesAdapterIT.java:66]: Maybe it is good idea to put this into beforeEach method. If it is directory also create it in that method using TempDir.

**Review by morazow — CHANGES_REQUESTED** [review]

File: src/test/java/com/exasol/adapter/document/files/AbstractDocumentFilesAdapterIT.java [hunk 4]
```diff
@@ -102,65 +119,75 @@ void testJsonDataTypesAsJson() throws SQLException {
...
             );
         }
     }
 
-    // @Test //TODO re-enable when SUPPORT-18306 is fixed; See #41
-    void testFilterWithOrOnSourceReference() {
-        createJsonVirtualSchema();
-        final String query = "SELECT ID FROM " + TEST_SCHEMA
-                + ".BOOKS WHERE SOURCE_REFERENCE = 'testData-1.json' OR SOURCE_REFERENCE = 'testData-2.json' ORDER BY SOURCE_REFERENCE ASC";
+    // @Test //TODO re-enable when SPOT-11018 is fixed; See #41
```
Comment (morazow) [inline src/test/java/com/exasol/adapter/document/files/AbstractDocumentFilesAdapterIT.java:151]: :+1:

File: src/test/java/com/exasol/adapter/document/files/AbstractDocumentFilesAdapterIT.java [hunk 5]
```diff
@@ -268,14 +295,14 @@ void profile(final RunnableWithException methodUnderTest) throws Exception {
         }
     }
 
-    private void createJsonVirtualSchema() {
-        createVirtualSchema(TEST_SCHEMA, "mapJsonFile.json");
+    private void createJsonVirtualSchema(final String dataFilesDirectory) throws IOException {
```
Comment (morazow) [inline src/test/java/com/exasol/adapter/document/files/AbstractDocumentFilesAdapterIT.java:298]:
```suggestion
    private void createJsonVirtualSchema() throws IOException {
```

Comment (morazow) [reply src/test/java/com/exasol/adapter/document/files/AbstractDocumentFilesAdapterIT.java:298]: I think this can be removed now.

**Review by morazow — DISMISSED** [review]
Approved with minor suggestion to remove unused parameter.

**Review by morazow — DISMISSED** [review]

**Review by morazow — APPROVED** [review]
