### PR TITLE
#169: Adapt shared tests to bugfix in Exasol DB

### LINKED ISSUE #169: Adapt shared integration tests to bugfix in Exasol
Shared integration test `refreshVirtualSchemaReadsIgnoresNonSchemaChanges()` verifies bug https://exasol.my.site.com/s/article/Changelog-content-20991 in Exasol. Exasol DB 7.1.29 fixes this bug, so the test starts to fail. Once the bug is also fixed in Exasol v8, we need to adapt the test, so that it works again with both versions 7.1 and 8.

Example failure:

https://github.com/exasol/azure-blob-storage-document-files-virtual-schema/actions/runs/10157083530/job/28086578191?pr=62

```
Error:  com.exasol.adapter.document.files.AbsDocumentFilesAdapterIT.refreshVirtualSchemaReadsIgnoresNonSchemaChanges -- Time elapsed: 20.20 s <<< FAILURE!
org.opentest4j.AssertionFailedError: Expected java.lang.IllegalStateException to be thrown, but nothing was thrown.
	at com.exasol.adapter.document.files.AbstractDocumentFilesAdapterIT.refreshVirtualSchemaReadsIgnoresNonSchemaChanges(AbstractDocumentFilesAdapterIT.java:941)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
```

### PR DESCRIPTION
**Pull request by kaklakariada**
Closes #169

### CODE REVIEW

File: src/test/java/com/exasol/adapter/document/files/AbstractDocumentFilesAdapterIT.java [hunk 1]
```diff
@@ -936,13 +936,8 @@ public void refreshVirtualSchemaReadsIgnoresNonSchemaChanges() {
...
         refreshVirtualSchema("TEST");
-        // This should succeed and return the truncate value but fails due to a bug in Exasol:
-        // https://exasol.my.site.com/s/article/Changelog-content-20991
-        final Exception exception = assertThrows(IllegalStateException.class,
-                () -> this.assertQuery("SELECT * FROM TEST.BOOKS",
-                        ResultSetStructureMatcher.table("VARCHAR").row("short").row("very_l").matches()));
-        assertThat(exception.getMessage(), containsString(
-                "OverflowException: E-VSD-38: A value for column 'EXA_COL' exceeded the configured varcharColumnSize of 6."));
+
+        this.assertQuery("SELECT * FROM TEST.BOOKS", table("VARCHAR").row("short").row("very_l").matches());
```
Comment (ckunki) [inline src/test/java/com/exasol/adapter/document/files/AbstractDocumentFilesAdapterIT.java:940]: I think the name `refreshVirtualSchemaReadsIgnoresNonSchemaChanges` of the test case still reflects the old semantics. Maybe we should rename it? 

Additionally, I wonder: How could / can the VSDF identify the version of the Exasol database? 
Or is this up to the concrete implementations inheriting from VSDF?

In any way: Can and should the VSDF at least signal, which versions of Exasol database are supported or which include the bug and which fix it?

**Review by ckunki — CHANGES_REQUESTED** [review]
